// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one

INSERT INTO messages (
    user_id,
    username,
    content
)
VALUES ($1, $2, $3)
RETURNING id, user_id, username, content, created_at
`

type CreateMessageParams struct {
	UserID   int64
	Username string
	Content  string
}

// sqlc/queries/messages.sql
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.UserID, arg.Username, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getLastMessages = `-- name: GetLastMessages :many
SELECT id, user_id, username, content, created_at
FROM messages
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetLastMessages(ctx context.Context, limit int32) ([]Message, error) {
	rows, err := q.db.Query(ctx, getLastMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByUserID = `-- name: GetMessagesByUserID :many
SELECT id, user_id, username, content, created_at
FROM messages
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetMessagesByUserIDParams struct {
	UserID int64
	Limit  int32
}

func (q *Queries) GetMessagesByUserID(ctx context.Context, arg GetMessagesByUserIDParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
