// Code generated by sqlc. DO NOT EDIT.
package db

import (
	"context"
	"time"
)

const createMessage = `
INSERT INTO messages (user_id, username, content)
VALUES ($1, $2, $3)
RETURNING id, user_id, username, content, created_at
`

type CreateMessageParams struct {
	UserID   int64
	Username string
	Content  string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.UserID, arg.Username, arg.Content)
	var m Message
	err := row.Scan(&m.ID, &m.UserID, &m.Username, &m.Content, &m.CreatedAt)
	return m, err
}

const getLastMessages = `
SELECT id, user_id, username, content, created_at
FROM messages
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetLastMessages(ctx context.Context, limit int32) ([]Message, error) {
	rows, err := q.db.Query(ctx, getLastMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var messages []Message
	for rows.Next() {
		var m Message
		if err := rows.Scan(&m.ID, &m.UserID, &m.Username, &m.Content, &m.CreatedAt); err != nil {
			return nil, err
		}
		messages = append(messages, m)
	}
	return messages, rows.Err()
}

const getMessagesByUserID = `
SELECT id, user_id, username, content, created_at
FROM messages
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetMessagesByUserIDParams struct {
	UserID int64
	Limit  int32
}

func (q *Queries) GetMessagesByUserID(ctx context.Context, arg GetMessagesByUserIDParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var messages []Message
	for rows.Next() {
		var m Message
		if err := rows.Scan(&m.ID, &m.UserID, &m.Username, &m.Content, &m.CreatedAt); err != nil {
			return nil, err
		}
		messages = append(messages, m)
	}
	return messages, rows.Err()
}

// Ensure time import is used
var _ = time.Now
