// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        int64
	UserID    int64
	Username  string
	Content   string
	CreatedAt pgtype.Timestamp
}
